services:
  db:
    image: dhi.io/postgres:18
    container_name: michi_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_ADMIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: valkey/valkey:9
    container_name: michi_valkey
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - valkey_data:/var/lib/valkey/data

  web:
    image: michi-web:latest
    container_name: michi_web
    restart: always
    env_file:
      - .env.prod
    ports:
      - '3000:8000'

  api:
    image: michi-api:latest
    container_name: michi_api
    restart: always
    env_file:
      - .env.prod
    ports:
      - '5252:5252'

  workers:
    image: michi-workers:latest
    container_name: michi_workers
    env_file:
      - .env.prod
    restart: always

volumes:
  postgres_data:
  valkey_data:
